-- dont really know where to put this, so here is fine :)
vim.g.bufferline = { animation = false, icons = false, icon_close_tab = '', clickable = false }
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
require('plugins')
require('lv-globals')
require('lv-utils')
vim.cmd('luafile ~/.config/nvim/lv-settings.lua')
require('lv-autocommands')
require('settings')
require('keymappings')
require('colorscheme')
require('lv-lir')
require('lv-galaxyline')
require('lv-comment')
require('lv-barbar')
require('lv-dashboard')
require('lv-telescope')
require('lv-completion')
require('lv-gitsigns')
require('lv-treesitter')
--require('lv-autopairs')
require('lv-autosession')
require('lv-symbols')
require('lv-whichkey')

vim.cmd('source ~/.config/nvim/vimscript/functions.vim')

-- LSP
require('lsp')
require('lsp.bash-ls')
require('lsp.clangd')
require('lsp.css-ls')
require('lsp.docker-ls')
require('lsp.go-ls')
require('lsp.html-ls')
require('lsp.js-ts-ls')
require('lsp.json-ls')
require('lsp.lua-ls')
require('lsp.php-ls')
require('lsp.python-ls')
require('lsp.rust-ls')
require('lsp.vim-ls')
require('lsp.yaml-ls')